# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
platform :ios, '8.0'
use_frameworks!

target 'UrgentCare Work' do
#    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
#    pod 'FDTake', '~> 0.2.4'
#    pod 'SVProgressHUD'
#    pod 'Reachability', '~> 3.1.1'
#    pod 'SDWebImage', '~> 3.7.1'
#    pod 'IQKeyboardManager'
#    pod 'Fabric'
#    pod 'Crashlytics'
#    pod 'GoogleMaps'
#    pod 'Alamofire', '~> 3.0'
#    pod 'ObjectMapper', '~> 0.18'
#    pod 'RealmSwift'
#    pod 'ChameleonFramework/Swift'
#    pod 'PromiseKit', '3.0.2'
#    pod 'UIAlertController+Blocks', '0.9'
#    pod 'XCGLogger', '3.2'
#    pod 'SFRoundProgressCounterView'
#    pod 'TTTAttributedLabel'
#    pod 'Socket.IO-Client-Swift', '~> 5.2.3' # Or latest version
#    pod 'OpenTok'
#    pod 'Google/CloudMessaging'
end

target 'UrgentCare WorkTests' do

end

target 'UrgentCare WorkUITests' do

end

