# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target 'Telehealth' do
    pod 'Alamofire', '~> 3.0'
    pod 'SwiftyJSON'
    pod 'Socket.IO-Client-Swift', '~> 5.2.3'
    pod 'ObjectMapper', '~> 0.18'
    pod 'RealmSwift'
    #pod 'Google/CloudMessaging'
    pod 'Firebase’
    pod 'Firebase/Messaging'
end

target 'TelehealthTests' do

end

target 'TelehealthUITests' do

end

