# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target 'Telehealth' do
	pod 'Alamofire', '~> 2.0'
 	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Socket.IO-Client-Swift', '~> 3.1.3' # Or latest version
    
end

target 'TelehealthTests' do

end

target 'TelehealthUITests' do

end

