# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target 'Telehealth' do
	pod 'Alamofire', '~> 3.0'
 	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Socket.IO-Client-Swift', '~> 5.2.3' # Or latest version
    pod 'ObjectMapper', '~> 0.18'
#    pod 'RealmSwift'

	
end

target 'TelehealthTests' do

end

target 'TelehealthUITests' do

end

