# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!


target 'UrgentCare Sport' do
	pod 'Alamofire', '~> 2.0'
 	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    
end

target 'UrgentCare SportTests' do

end

target 'UrgentCare SportUITests' do

end

