# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
platform :ios, '8.0'
use_frameworks!

target 'UrgentCare Work' do
	pod 'Alamofire', '~> 2.0'
 	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'UrgentCare WorkTests' do

end

target 'UrgentCare WorkUITests' do

end

